# This is a basic workflow to help you get started with Actions

name: Test Workflow

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  connect:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      #output2: ${{ steps.step2.outputs.test }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: step1
        name: Connect to server
        run: echo "::set-output name=test::df -h | grep '0%'"
      - id: randomemail
        name: Create a file
        run: echo "hello world!" > email.txt
      - id: step2
        name: Test email
        run: curl --ssl-reqd --url 'smtps://smtp.gmail.com:465'  --user 'carlos.pelimer.caballero@gmail.com:Minato20' --mail-from 'carlos.pelimer.caballero@gmail.com' --mail-rcpt 'carlospcaballero@outlook.com'  --upload-file mail.txt
  recheck:
   runs-on: ubuntu-latest
   needs: connect
   steps:
     - run: ${{needs.connect.outputs.output1}}
